apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - actualserver/ks.yaml
  - authelia/ks.yaml
  - gitea/ks.yaml
  - jellyfin/ks.yaml
  - nextcloud/ks.yaml
  - pgadmin/ks.yaml
  - teamspeak3/ks.yaml
  - mongo
  - external-apps
  - watcharr/ks.yaml
