apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-adventurelog-front
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/external-apps/external-adventurelog-front/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

