apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-your-spotify/ks.yaml
  - external-forum/ks.yaml
  - external-somnia-customers/ks.yaml
  - external-karakeep/ks.yaml
  - external-stirling/ks.yaml
  - external-lldap-web/ks.yaml
  - external-shinobi/ks.yaml
