apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XFn/KxVIQnBFk+rD/C0HWhACsGZbEHgpDf+hCsf4DZuJXK2VTY2GaIafbDiY+qeCx619Nm0oaUbIn0tKHxlBcp6lGsC4uza/NG+z40rgm31WsJRsForV+DJagwd1ut3J/zvGP2uCIqkh0i9qsxq+A5on8Zt0yUOmOnIvpXS+Q+ViTYHh30guFVsROIccA4iMsHFmk24Wtc+eHee8Hq0Bj6UVMLQBoyLw2omqWczY2BWw2LBfNJJVbGsrJdAPB7vEsUliOMW71fVFb/kiViPNgnO0IPCwbqrKUyOG0D7evIh3MiChAROOyaoZrmpK5PnGtS68sKrasnZhSuHJnxkCGbAcrnTj/pfzJUEbApZNP+d9UZhrMLHNX32w1EvDXYuT,iv:bKVv+rdXOoMm5V2QgPhoFNfTduE8UL1GTLv5IsDDTgQ=,tag:2VWkEUuA3h7ufzaMTF9uow==,type:str]
    identity.pub: ENC[AES256_GCM,data:fms5NyoUCFXedsh9g0hXeu2m5bMS3uifcwUWS+P7RerkQJb2bCPFe4MxlqJQKW3SyqMmZ79jiNXgXxtPXTENGFBzzL8vg9D6E9CIJjffWuTX6Ae9bHv29/+gTKGaJ862CtBU4TGatx029rqSLMVYI8hCmQpaU5Z4NxFD7p7m0RCCnP1kI3DMbF+wsxJNmlir0scuD79H1xlgNb4BWiLQEj1+rpdQfcm2dTr5p/3xonoQQsy6ko87Vwt0t+Ks+zKnC49Gyarz9BYO5Bs7KQ==,iv:1t84nciHysy4DakIuhygRTr+zF+GfUUimzKVQPhXs6s=,tag:nOh0wdx2YY0jadVCffuL9Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:ogB/yAPMLHe7E1FuNpWHk/08DxZVjSnUdT4WkTwwURH+KuxmwAdG4lDCzsNNpslFsNHCY3rUB0U0ylcpVHhgz2d0qVcNv5yuJSeRxAO4ugSMH6dQ8g6SeTPxBCPyraLyDAllebUJi/NOjtQ8kcfhO8RqZpIenknTJ10AOp896ZCSnS7CK5RE3v/Q7xPuOktuaPF46TGOIdLIzWFqKtI2aQOmTNl0dWHIlNhB,iv:YTyjU6+tT8tby0g82FmRfOyk5JC9d2g/VRMniemiVLY=,tag:PLJjRmBgaj8Z7yH628jw8A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQW8zTXBSV0twcmpWVEFr
            VWxoeFk4Qm1WMmNEMEx2b1huS2N1cUdFUFU4CmdtOEN6QytnUmx5MmMzV3A5NmJy
            OVh0NTBpUGNKb24wRmltVkt3UjFSQU0KLS0tIDRKS2wxUFZEL3hraENpbWFhTllX
            RDZ4cFV2Uy9BaENXTnFENXpFNm54Q28Kw/V7lfblWFUKiAi+I47gb39J0BrWt22C
            nNW6YNsFcmnpTu+Mpck+U5clS88B7eyGFqj8SVbO3hTlxLKWoiYNTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T18:28:07Z"
    mac: ENC[AES256_GCM,data:5Em9cvRLDQTsMGCQnXCKlWcJCHkVEiLd7bwcpNmlE8LN3qs9/a+d1dGPdhlL+vnO66zvAXOyBuGw7jJZ6FMwJnIu87vE0eLBG7YxsCEjxLa/Kx6H2+MdSuiGfz9SOPkyiwCvSnWXIQSUIX/vq4/ubOFpbZy8NBY2VLHKQ4JrbH0=,iv:+vGu3XPb8J2eaex6uz3+G5Btl/WQ7yoFjJprZh8SNJM=,tag:+gxD6/O593OjfNo/Agqrxg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
