apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jCnkmxL0k44CktnsdGwsZESv3x2KKY3Tv5L0KBCLytrv5pjV8+Tblxd6azKnSApfeeDV2up3Vj/TpNUE/aPlMkqQbMeM+GfUuU6bA1+z+chROhaMlkr4WcpZ6+RF20Bbvns1EBbs0ouP68/yCO5+16exV9jMEevDBRfLhCNqoKfWcJs5UxDoOKl3SxYZyFKE8hm3/TG3iFSFAgFpVWI0gepjunQwCb9cMxeFTMgGjg8nuzCSkDrApEn6yjgaERIHPPE7YIVLb0sggAj6XcHqlvqtXfAPgKk3hCmcIEoknSdBtbRI7uL4DCWCZYndpyT1o/jDQ4UKqYdw8lkKd3I5amde27xpoY4YONnU33VhAEAorlTVy4d89lFTCdttcjQi,iv:zuEqcUcsv7Hvx1aUuScvIK54SfXmA3/Xh5oaLxcfMws=,tag:jdqOM0/nGgX9BbeYeCd8ww==,type:str]
    identity.pub: ENC[AES256_GCM,data:8QeBmU03yxuROsto2yCDx7ltdqCdDFhGFhNX4aDR3/HwCjbqmR8zdRheLWLDDZrxDpAJ2S11NRabEitDsN3G1pI2z8nYtUgGDtSf73KqCHAXiNqeL/2I3uck32ATzWOSvh4pQEh2uMCTfIdhLGx/vkwmFP5EGIz58d/eh2l8c7ED7KwSRwZRl/Ddhnl8IKlxCvg5iPAmeOODMOdJZ8yuyzaPeYKR75eb7sYy4ebCxEYMplZHjHk00IzfEKSkla/1ASQ3Cd4Q3aPoXcFLyA==,iv:l8RJoHbLk6fe9jhl8sqUCjMoZR0sHux0++zvCrxKYgA=,tag:6QcMRxyVcvPKBfJ8glESNg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xb83U0brPtK5RUTsrgCU1Yi8hIkfzMPBgS6oBHm99wByMdE3rEA6+l1RsvRKP5+APXM1IIy1BruDQGwUSZSdQmf9eCQPrZe1upPuKJBIMOP8+BoKwTCH0IVVG8Vj7WB+I3XNo6tdbbGFcHsh5bd/KreqyHcLlp3NT3EioYWNsi1rRIlQJFhCk8bW5ltkZVAS6gcIKnKjmJLQJ31r1ENRxGArSe/8DsFV4LoB,iv:0JYiQAj5e4z0xN2kc5Pt2uP1hliXxcsAC57OuHUI/m0=,tag:bryxxvwymLugmmUf3g8mPg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ejZ1bE42ekJuSXlSbit1
            REF4MmcvVmFFTXliNGNla1k2bmtBUlBjeUVvCmxsZ1JCaFEzOG5wU1MyMnVITVNk
            VUY2bEovVysvWjFQbC9rTFM4YjQzMUEKLS0tIFJsaW1pbUp1d2xsUDNqTmpVNUhF
            VS9BbmR0VmMyZGVQZkw5NE5WOGFUMDAK5kkewOnKdLYLmqbLvd8GoxyxOaBvs2YN
            T6gxb6ZGNumcyEpBNk/VvyBYh6CXlN0emkjAJy92mpo/x92lPjkHCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T19:51:05Z"
    mac: ENC[AES256_GCM,data:1m2jak4d9Qtg7fhf7sTaGlWOg0e+UkHq3mIJ/RyeRc9dWaZ5WgkY8F/3ESLDnccFqnyW2dJf7y/FZkcSL+OnLlhPVCtVWNnxPb/C2wsVE4qXM+UnP5iQWKXa118u/QkIg3cLq41szJS+K+V7HsUhpX9eVfjOXYZ5Ixs1HRIOQWk=,iv:byzktUgthYFs3dkpzzQXv4q/8hG7kSDZw6FujlXeVSM=,tag:urmzKlqyvVIbducfCEgYaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
