apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:S1MArJzn/0hseOBB4LshKs2QKNB3HMaQlnbMdQR7wwxOXj8DgIhoiEVGQwJ0IKL+gAV8RuhZkPFoD3beiAFWe21vxdGzGrdrry/04Mujk6ZbRTzuPFRcmdUB8TkcfRbKYi1DXgNecz+RruWWfn2CdofKuPSWQZDZkSPwwm1y5Wr8agI9pP/p0Me1ohpXvmwmNXeJHFpvpQGtoJ87mofa5jF7JQ9wj5rT0VnNG+ofzBtVIFMjhMIF5P+rBCLglVIHwuZIItSU5wwNZB7jM0KEp/yhtNdb3sU0AAuMIsvCgdo0RlDRonERuyRnHtulqgTIHdf8ITdSwT1y7CLWBqeBGKT1JH5+/Rs1ucUmlJ8DIgFmlFXKu4nfc3z/9Zt0gXxX,iv:6/5LSRTvcQ0DIO38OrEWfZhc3HCuEV+5eQNw8gSAv0c=,tag:sbrr10QkSCyHs+lqdE34Pw==,type:str]
    identity.pub: ENC[AES256_GCM,data:7EPabOI0+0M7BcijBYpZtMEp7+iUdVDEzVWmtnut3BATTnf3Xzar54yB3G3wQUBuqLuKosqxkJdq/7AD1wGvjPzEDOK8JZsKOT/Zoiqy3hwR1pS3nf4H/+afdQZiPW4aL1lST5FbRV37fCdmd2hz8AABJruYDHdDRW2Om8XicIb7Wm3RhyM02jlR+gojyWbhZBob5tUKcJWORapYdiS3NKMzctVkBlq6SqnNya6pvtCIWjtwo3UYLUC2bp2NJ9XMteHIDWW/cY+1ZLEnMw==,iv:GkgFRP8s35M9QuyoVuB7Rvo0qDeB1P2LWbvn2On3//4=,tag:pM7kyiSLDWZShjzss6Tx4A==,type:str]
    known_hosts: ENC[AES256_GCM,data:PLV8uGZYFPb18zs9LlBEriWT1CTo2AJUlW0xFtZQ6hzmNQUIu06iSkbsx+przh+1kvgQ4o9oT4DOqfuO0EpQbSeps4ucdKW59DZxqxuCe55hLTnkKs8c4aWDT5hDUaVr0RQwAKZDMw52NKFUobti4GGqJbhSYYLFaTXyVS/1P2aagAREuIvipZUZfIny/OLOGNlyfo3Yo/AXc8x5F3kuX1SzaikzKj/Z/D67,iv:t+rlXFYbWzwllkyf2tHrUcSGJ7R8EK5wvxE7yQFd30A=,tag:WUrS6r6V4TSR13sDX1E9bA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcDBhK2VsN1NVYWFGZnZv
            Ym1GTWkxRjgrcW84SUNzZEFqTWlDSmhHWFFRCnplNlRSSkc1RktDS0Q4amx6b1ZJ
            WVNKbndFTTNEYy9pd2tJczJzQ29WUUUKLS0tIGZBRHJnOG1zZ0FWYXFFdGNteTUw
            UnVhOHFiTzE1VkZIRDY3QlVkdjl4WlkKyqNkTwO4GjWksK5H307v6gX4uXdphzFB
            hktr+t3AVg2pIERaH+MAG7VdhpMyIRoyaT4vQjp26sq5sWM1UoSqbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T14:30:37Z"
    mac: ENC[AES256_GCM,data:8mMZjpLtYKLoY87Nqp6+uIsGiD/8YRwuDFo9MoQ21NDKpKsQ6e45gJkWylN1/SiW3Z+t8bTSCXGUk/b/o8ofMIjMpVbxYFbTG3wmMcCU/DT8ijv9tvFeAsjb3arEecNEvRAVWorPEnph3/7Wa84Oa5mYqPFAtNAJJAyybTUl3HU=,iv:XNOEs4Sd7uiOFuVaYIgwnjBnaXzAwLvcADspjtxt0bE=,tag:5oS3cbEno1mW1dbMiZeK4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
