apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TzLjCcItdLdwOMcqfxo5pMsEO21scAmRxgXtx70KuYsKtM4ZuQR6aJoW+KQT7tUz4eUYJ3eolCrjH7cG1bc8FmlGznGnFtdswKg7iBf/TLunl9SbRDa2yJy44uB97gYSDbIIzworpJU4Fzfap93FNSMYUb+rNzweJ/uAaOiHwnJq1ip91QlgzCVzUbQapvSCe/4sBHw97I6Ygl+TQatZKJyxN5itjaiTFzhnYi+2pONw96smRPfXlPrmlY22z3RHF2G7GmT5SMLcU1ndgwo1HV+RZxf/7xmVBMGgQ0lPMG5XhkURHbGaS2G/f3uD08qzRd5MeFEciruWJ8ua4q/azEuokigbo06/EEZ7mA4oIZwh3+44rWDuKOz0b3ksbvmI,iv:1z7SysvZw9iitUaRdH543whWR/hSQObdKnJHrIrLXks=,tag:9/e/+akoV9snd4TmZBqr6Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:ayw2IRuGbWPf25oV3Kc7bfAeVUvT7hiH0ZAELjZsVGq11AoFiMpriBFAqwIFoddb7KWQGQRFReq5WFneqSz8HFUuT35YtDkNLzgSRvNh6a0GS4TELRl+m4jP6N04pI/bO6lJfjLnzlhqhn10zt2HXihk8nVxSNKy2OqQYrD5VwzD0g3nuAlJ4lZBQgMnsnuExMYRudAvL+6xO2hljg5yIuXRRGtbbvn5uj4zviLUQCFIvYE12F3YPMJ3xbdbo9/jWi6HoLRHdpObXYSmwQ==,iv:Du00FMDR7l8MMvSD8dfsH4kmCo2moLIZLl2dxHlfa/w=,tag:e/BPka3wkeupqoknifDozA==,type:str]
    known_hosts: ENC[AES256_GCM,data:d1lY1n+NgeosENOXCdw2XuAvyhEPqmSFgzWWnzy6YJJPi1JPB8u5bCEQ4IEuvnEyYp+3kDBVJ8hcgE39CxfYtoALucEPAVSZMgYqi3P87yhmZ+DkLDfKmqBdffrUta4tf+2kfDcamYbCBvmgIC7udr5k9A1LULb3BF0koEzvqGUGhqZT1xW9JRgV3ZuEsF4m9puMdfPNuXD2rf0M7yQPKVhLYaStBvov4Ytb,iv:etalDJ0k79NImf6RTF6Ifo6520z6FpYrBMKppJ2VenY=,tag:hd9YR7zabiyLVWqmAeeS0A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RTM0R0JoNjlJQTJTVmQx
            NHRJNHA5dzNTUmFHMGdGcnhqQlhRR283V1JRCjJSditEMGpwVkJ1aTRJdXpsUGtk
            cHZ2dUNudGtMQ01TRlBEalJUd0RhaFUKLS0tIFU0NXExY25GWnN3TnBwcFFldnR5
            dWo2WXJGOURybjFyVkZzQ2JHemR0YkUKehsVtGREm2pNbcF5vrKlVZ5QmKZltIxu
            VrEpmrPha7+sgFtyT5Twe+21kzPtlu6N2BGEP6Oxvhn2WKzguNFSUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T00:28:16Z"
    mac: ENC[AES256_GCM,data:KJKE1VnF22XF3RdBChvF+nv7OO1YlZ4n/teBKZ40wp+evLGxtn8+Vlq3+Ypij0lmB1P/Pnyapg32luSxiLgeTX7Fc7dTVlGNPy8HuofVXH/8HHzKJM8AZ9vCWfiYrXETVrzOZogC2eRxjr5qVkpmMGhfUuosnV/b9Eiox+xsCYE=,iv:1/l2tyZnmsgkgVS9timGLk7oPhERK3bwyKDZ6wCQ5L8=,tag:SZyeuTBu1+Qj+erRsLtl8Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
