apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5m4tYOC4vNVPMwV6EI5rfoNJzChKMgpCHZQt/LqNgD+eUJEjz86fcPb/hIO99tolxHd6xSWNZnC3FCsuMXipaFvhFt1929BVsZxhftT5DgEHfd8hObspJRFVq5VECmCfvU9m5GeXKOXOLQxyeHBUbCdPZkKsr7e/qx8V6da9APgoDjousfWtpaEVzfHjdf+63DdZuNg/ua+kEVr/ZsZEux703Ihc1tU2SJkhrRRsKat5O4WYz5OjeepG9CBdVUUZtiretWot5I93MObrqo+JfauX7FjHNw7S508qfn3ZRzw0mtQEJIIrLeuh9yqPyNkf7MMGKWN2QKsfctSRDuMfcDqDBMqL+3jCStzxw0MkstNeRxOzTBvHAZywUZXTLlAt,iv:VQtA9oORRxtNCtAc/VJEC05iqDaZedNPZkMTtU7HUL8=,tag:rn3ipPmlJsqtq/uKgZM6wA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PfFVgGDksVEYG9PyYTpao+S2ZKUmh7hLBuZSIBbVuZJYu/WkrgFWVR0FZBLRNEaZdGEWPtjhPGqlZ0Z8aBBnt4mALXSP4+FPp2jcu4kj/gpQcrLbRZmc4XR/2l1TWgFDNaY9K6UiJ0NrQzioI0SaRagToElqqnn3AMFwuHzsQrAFK0KMx5Vr6Uc35eUveI9bQTtTxqYSR02atxbkZdLIbPhfl4tUTEphAWHjULflTRexdwqbirdnt4W0r4EBa9ZdN+mowL/3ZuWNI48Cgg==,iv:H/4GkQ9ZzROHaNC06vzSx7AJ9PWytDIMy9sWpTq9MLs=,tag:IRMxWYUafzmkgPEmbUBsrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:5XuklPZFdNycFHWttdHzj2okHQUJS2ma9XDYHlh+/6fF5cWXWDZImTrOvMzYSRSiFm+iNMUB56otvz2i+h+Adn0k+G7iXI1FZ9a/ADwPSjmU/ouDZ0HIme4SqjdH4arJ+2DOiRZ6cLH3HfHe1v85ONDGJxrAqAH79XeuP4STH3a0B/t/go752ZGQxIXB5gwJmcZUH7DkN+HMoCOP6WBrLYdeeKCXhfXptNdQ,iv:VCj09wogpg3u907+s1Fkm6fyw/vzmx5RDvX4jGX+hyc=,tag:2z7I9liXuU+Vfr5/Uenflg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbThjRXpETWp1NVFKT0dq
            VlNqNDlDclk1VTdnUFl4ci9BZi8wYWFBRndJCjZQeC9rdGk3UUVTdW51SlZiTlZZ
            RTl2Y1M4WDFYa1Vzem5QR2hWbFdUTkEKLS0tIHhDOVRQeE1tU044RDViM1M1NjlH
            VXlnSXp6ODZvSkNIQ2EyUFNnWHpmL1UKmF4cs6qYbEAjnBNB841MhwMq3+D6QgmM
            VnK/IOCRdlQlVEZdVGX3sDpnhqCIzeG2VoS/vFX4bZNZrbH4IVcV7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T13:17:45Z"
    mac: ENC[AES256_GCM,data:ZjVyH+ClkUykfQe99kwQF6B0wfH7lB6Ms3+4iRMbuhsmwKcfTHc1k5x4dld1cCG+9rDScVD8pEzQG18fXvs2IC2gilQbmbj1vAxRPH3s3CA8925lTJiKEVujt8Ntd0MYhAxO4b4f1gDj+4cQJv4AtqdxKKuWIttjSwyfYsWidrA=,iv:b8IF2qScK/1/hycjwDiwR16k87FqAFrxzSE9WE2RNEE=,tag:nbF8o6cLRA9FEPzVEMobKg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
