apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dxwAcJpX9vCioGsxwzuu5FGgj1JdJ35d0+3YKNeaNOYvEyJAMcY1GT+nTAkg+/FuD3je0RWTUA5Y3B8DMJzLbWS6iG6WNYY1EAN7K4NcfiIA4UpVguZ+w4/i+G27B1MziL91tx1TwoA9+oHhoWB+1LgQ3n8corAqlMWU3MC/SB/anJMD0Q2w6VyApwmJgBXqXPE6mAeyNruDjEF82hDeTOnYkdqlqB1c8Szi+OrC/H/raG1GDiV6ZgSkgyPIQD5eLIhJvczZhKLpA1SFO7lzGtRQ4DlP4Fhpmw8+1GqSJZVaciV2rV0AANR5BkfnkQld/jIJA/Uyt15HZD4YFMHHe0Sadu48YK1UnnrU06qVsdzKVHuUC7LcTuXMF4LypgKz,iv:G21cpEnzWUuTzaBTlnEUMJv6iyoCdm3mrwW7AZmZe9Q=,tag:HAm1bn0DvaTqSstHMBpN1g==,type:str]
    identity.pub: ENC[AES256_GCM,data:9CzbV3cHPtLpOCoL5jXxKX2LCe6aqiK/Fd2g6NsbtRtpQrv3BOpKXsnx6ftt99vPn3tow/j/yRBeLSlA97xHjGUZ0rX+/nVEZoQgoIwV/4ltHdQhohKrjMqssQT62DJlOfU8+kn336C4jiSxwMr6wYdWdQToKt6CBIQlfwsmKukYmrRRtCSSPnMHiZRsN82kv86SQf28QCogHWVbmJ6iXjMQYiU6K7d7l/UrXDO6DPfLxUJaaBeZWQOnrxNVZVemLDiAk3ejmqwJOBKWwQ==,iv:krrL1N9fRH/GG4kf4DSGFs7sXKG6L2f2XnUQed88YC4=,tag:YO79k0nmavItXYlH4m6vOg==,type:str]
    known_hosts: ENC[AES256_GCM,data:1q2rI+6aEHibcVgUROPB41mxEy+tZoFJUCQnquontrtsBqIcBu1AxKGuFwppTprdR2nHC6OPVp8TzWsGK82WrjzdFbDQZXk2rvsGEFePBYukWSiNBWDC4gKaDKCdZwrhhkq3LLrrn+EZQYU9mw6jhx4SShG5kqmmQbj2tJNTqeKL8V3T8n8GECoHl9P8ukD/hheMPxm55nsbBzuF981dKJviJoQXY6XzLBaJ,iv:Uyb3Na99jX8FWBe9oebvYMs1IoIa0hkgbM/C9kjRquc=,tag:t05jjSxdeDVIIGjIj9bM9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUVA1M3NyRFAwVkFVcGh1
            S1F5dk0yeEEzNXo3Y093aWZqdUdaSzBJYkdVCkI4eGl3WnNvekFDVEZXMWZxV3hM
            V0hNMnBjNFlFSkU0YjJUakxGazYvaG8KLS0tIFVLcDVhU1hKRXo2Skc0UzdBQnRI
            Mm84WDlScW40ZVpJVlJaM1JHS1BjVVkKWcTQe497MoWNf6LcqtTykW06tD2GGB2h
            q5DIi76qwI69RF7fZPJBQO2XCwHOIwrpaOuKCh73wc3XS78OMceuhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T20:30:43Z"
    mac: ENC[AES256_GCM,data:XoWvPwlscS5zMSQR7eFlsTGeUMYeg/Lecps/89Xq6iU2HAzE4eH2eDob+T3ow7wYcgvGaAM26QTckQ51NOtjfWde2Enb45RsGZ3ju3UD2JZXSV13XJaIX85EiK3ugJds1//W1s5cLpSjMdEWCyERivK/lC32Vf9GRwvj6Kn9qFs=,iv:tsWkP0canAlocU0ASlF87eMph5AtBGUdDXkj51YdurI=,tag:ELmmCzja7wP2J/zWmvcluw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
