apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MXqPXQgzDWMKySsDWZNWX6w7EcB7LBn/mTKf5+4voG45m/fqAOJQTYUD1qcH6X7dxKuMUjIGm+UVz5DqHzSqGirf3TKl2VHeL8sm/CDaCoAeLRe9SelOlMfWoQmXMAEPJJplzDsq+et0keHLF0O7HqDbyfm2o7VuYWzPpfXQVLAxypgTRkZnE7n1UPiwwVk12DEBxL749BAVTkTJM/KozAA5x4ox7zmDcq3Kzmwf+NEHGUHC7rvvhAgxuKmAWlMO+wVwMKNmFG1FUn+iUlp2xBQz/geJGyXCt5G0b+FuInwdtWn4dR1zxR+Dv5uaU/jO1IOx0Mj+XJXmum2fqiPxvak0hYy4NolVwyr+tIroQmxgT2To/0dC7mnzqApUUt2f,iv:rhsl30NYMig+1pcBOZjlENe02661sj9asI+e0kHHDqc=,tag:bI0mnIfRxAY4ZuR22OAlqg==,type:str]
    identity.pub: ENC[AES256_GCM,data:TRcY5cY2tiY1x6I8iNE+2RjNyKLZ3H6fPF0yELdN8ODaccQps0Jr9vF8giasAXptBQYr8Hb6vyssP74gO2HibLzxdXLfWoxTlAL5yxGEUZFcj2OthvwF1NIRhpwXtMolmO2fJ8ULsePceJ7uf8UrTbwvDusSo/F3KfESgIYFOHDbKniHmWBgfnD1fhBHZzshTK4Eep+hM89JCp7LFiR5f6/dW8uFctNpGuAyFUgeIJcElCSc9vEisZzo5hbrVLs113/1Hsw4Wll1iupI2g==,iv:cGkVtZBtN21rAA1yGpxG499CGBt3F+XTyUJSTFsLlX8=,tag:NZt3adqd9blR3UkPm6N6NA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Idluu6c/sNalqi9b/WZsKLvu4+Urtk+S86T816Fckpxld5T4NnQJW00/q3QVwUEPDv/lVMvp5Q2kh/eg/QyUL19yEt/7rssIP4GJTzs6WDk1JcsANQr54wd3xsIZ0KZ3PnW/HGWlKcmppThWxjkcDladun3qjAbDqX9pzwGmgdhHobty5xjtiJgWVFgl+49I72qxscm5NJkEJrKTJ+/kkCH2wkVhgoJxLEUK,iv:ecWoUEOsN04MIgMhqrUTMWS1W+dacc+cQuiFksotxbw=,tag:Omf6NF/uc1HFNj2SRuZitw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL25tOXl3Tzk5T2Q2WEN2
            cnUzQkluYWtWK0lDQ0RaSTA4cUt4ZlpGNXdjCi9CWCtqcVIxc21jOWlKVVpaUkFh
            ck5IVlQwK3JIMmFWNWthNEpoblpTZjAKLS0tIDZiYVBpdXVTNDg5d25mYzRXYkdt
            OG5kZXAyRS9DLzhWemt2b2tvRVorOGMKD06CcN9k6ow/Y9r++kt+rXjrv8RXSItY
            0mygcaVlbeZQ6TFfv+yGuljcPFtvPprjMifcgy+5PerCXLLvaIS5Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:19:22Z"
    mac: ENC[AES256_GCM,data:e2VtkrI0AQzawrKlM1Pduc53VN5/33zxKqaRcm1jU3uu4Fe4n8dfg1LHtqRF3+BSfW+1NzOOlcLnodafU6chrAuSXoqauTthqYtISMAVoNKF1gwZ39Y4p6cRHjEKXs4eMnSpvyf1TZbJhZs2Lm9WY/nnSxHMS/xTDStNq9RdHr8=,iv:5lrt0Nj5GO28fh04eFlWg4+NwzY6ksmSmwMSaVO+M2Y=,tag:TpjC7rQHWqpTDAa9pMu/ng==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
