apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LRF14M/1+BivEB4N0TbgjXlsCIWwrYD7BObAqIjRqN2b2ChCXujQgYPehkxp70erZ/cKljmyzOzjIYFlxl5ZWkSp3D1xPMJIZ1ZckWtZ0QF47PsrUbzG0coJVwcH0UkTr6aINqPbIKHgUJk5mns70N8SjMi323BFrnVKkXz3lpSu2OW7j2tgVvV3hoqguZv5gPcbZ4iHy5xIImX41jQU3T6wYWAeu34LRmPkqulnKkpHLQgkTDKrvRqBPbhYQes3ECkFVsWympcOFXYYdweaQ9CO5rSF5daMZvEAbE2J6xBgy9Y6QdOEuyK4i+bQuU8xOhEU4PjdXEl7hJHbJA6JAHD+zH8nOYJ+aWVUD5Xl21xqUs0eLbx5xkRJkr2zr/PZ,iv:+zkAqTzTTmVEchn69h8gdFMOsLEZM2D4UEPp8JEDQ1A=,tag:U4QbLryhLtxV3NFbGYIarQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:alvekmH5kXQLKhv3d7ouzDioXWoXqJCwcyFvxVYp3+26YYpDq1cCGP+buhcW8guoX4mRBCnUvb5eZ7ofY+6VD9dKQwAWZaEj9qpKeMq/rYklqJi9B2U/fw1/Pzf47RwzT0MX0TnjsCCkaHBo/OoiYiKS8mRmCTnanqut8VbKIxSz+b4DBdufRPd7yCYesKMwfSRDmeQXWeGYbvN6lUFZSLzHB8LCfMURjN+HTro3RHkxTnTvG0FBZ5YdBuRO6pSJ7J+RS/aye6cNvz+I4g==,iv:0KD9KNnGa/TT1PvQmUEFuQRbk7zlwPM4QrztmyQK+pE=,tag:lhnUAENwIOe0ElfX2Y0iOw==,type:str]
    known_hosts: ENC[AES256_GCM,data:aH/LJDomDtYYHeKNBRn1ltcHOh6o0efqHh7mi8VFJjatQ0k4rrU9JGQUcY1taLsyBOv/KeX4nboWK4PfoS1bIxyH1Q0su4YvM3B6avUV/zsHYgCvDiELZob6Zo5cX71ZAWMBoZWsc60ciw9GPcbpvYd/ECRkiPT9esrKZC9F+Tm4ZLlCRgroBmuguKb01OhtKGmG6ZxWjW7wRl/nYHMoLK4F6uk7RYHKfjpf,iv:Q5Y2MHOZenYiqwSFCKZSBzt/WityOj0dS8IdxpP1MXk=,tag:FsNyIfEK0o9aYCR8FjtdwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlekljMjBXYlVYQ2lLamlG
            eG9zcmVpSlBSOVRtSHBxL1FIUDl4STQrd1gwCms3S0U1WmFxNHA1Vm9pQXkrSE5T
            RmpvdjNDVVh5Ykhvdjh3bkExS1lwSkUKLS0tIE9GbHhyNk5HTno5RW1SdWplSkln
            Tkl4d2JMTWtCVW1OcGFObThXS09iNUkKliIhCEEdplCpNvtnpErI1RWXXkruJM4E
            q1wF1hi/ac2REysMLRt7oB4xW9EHjCYeSd0cOtf9ofjLAjwCh+lU1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T21:16:32Z"
    mac: ENC[AES256_GCM,data:IijkFEuQiSIiW2VL08NK5Ul67PM+yKMoJgeFrq8wZ6JClykl1EMa3hw8Vv8vlZwbBkS69j+OO6fdMybnbjnIA1nE4DbTJy1NmC/ZVnDrktK7Ua3oltT9h60LtMYZo4waVp2DK1T5Tzg35H3YSz6ca73uDnlxTGS2hXg8ZSbUXdQ=,iv:wZiJrVS8lw7ALPDCE1IMlaY18s2Z8C9X/S/U8gN7mN8=,tag:2uzXAFVKaDu/Sw9dnVJr+g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
