apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sMX+ftIATinf3rCEJVy6JrILjvxthEOMn4O3615SUVbTSf96YhdxFwFV+FbPKxb7RNijPV0TRaNJt+j++HPb/2yMMiEigBrSRAJ1V0SPrMN0AllPCyKmbEkEuiB5zi43Jy+QQmPzMB7TzL3v/DpB9T9nlUlyc5eRwRn85Ag7bfRzh4w29H6of4dGCIWy0T5qymcD9UH6WwRKVYkqIbsFompQDNNym3dsOJiOhdjIedcSkWDbHw6QmXGhgZHTKj8Bq8utYYPQtGuJok+3p+d90FcmojM8cuKVzmTXE7SkwDd1yWHwS6JCg8c8ABeemwa8/xRETbFt2q+AiMqM9wfJxmOVLoUNe55/5sewWM032MimXBNimKMjquBIiCOmej0r,iv:vOWhFVZVfdYZxJkqfXiSGnu10lo+MwJQYFjJEWgq9Yk=,tag:8Az4tSBxLOOYTxscsA67AQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:mhgM/1K1FqFlT04sI7NVr4OJ+j+HaCJO4Ytd716C/8r/3YWyKLe95ChuNHGCp5YHChFS3OhJkUasA90x9mduH9EMpBLwZdjciFkCJgGNe6+nNyuuKak0caCEqFYHvkiByeBGo4O3nANShF0V9ASn/QMvT7rPlgTne2g228UNZ96geVOy/pUkhjk8yqfPDRpSalR2/6eOg0RddtEhavlWYTEKzQvGFynJWZSZ6Cbsq68WA5a6CouzlCo+lMT64ff0MNmiX69cx45OCDCSjg==,iv:fxKbMzmjAnxxjLGp8KDePUH6zeNxXJjvTx0tN+LGpC0=,tag:JRhbrky6/diGhGf8ySZSwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:EO3wjtF5u7CbmbnaiRoaaO24jduAY4eSHvoZ8qgg9+o5oq1D0xsiu0fpgCH3c9Ahbi9qf1mo93VwZ+D7MxgI3t1UuPXqEFdeyVxpgd6CoOcbfJUG+TUCJY7GVHFVMtT7DSWFwWfbwtFhUNa1b2rkNSya2HLt45OTIS3OdBvustX5KaDuDnOb576gmiLsy72oNrsa5mI3zwkPRmMfM1CUApyIEVcgknrxAzGn,iv:o9YOx6ESqrRA4ggldaKNlTBWhDSFx5tGZSxl4JzDqIY=,tag:TY4eWC4HJO2J4rwPwCot7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY3hETzhQNWt0KzFVWlVB
            UHhTRDBaaW0xdGcxT004NEtVaXNPbjVRR2ljClhwYnFqVkhSeHpSNzVjMzBMaFc3
            ZEdzQjN2SHZDeXpmY1lFRXdkeXJWNkEKLS0tIEZmaUNmU3FwY1ZURS9vbUU3NUhN
            ZzcweEtHeERleU5Gd2FGOHUzRnJYSjgKDSPdyNNyOubQJZJDAMdGoE4Amew/QFgZ
            U4yhRSqisv6i/KHd3MPiTo7tW/VGrvJH3kujYq81mvaylUUSP1MMpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T11:48:09Z"
    mac: ENC[AES256_GCM,data:lKVlJBdf8oRDuJxAxPR47CrHx4CXCSu63h4XsvFDLf2h8v0H/1HYhp6uf02huKmBBe0qvs81+6XuWpY/OMGxYQ+/lzBajNB8fMd0ias1SOFwO0bFDg+hs0cRu/pr8dMi6aDwzrQ6YW8jaJ26p4Jo4Fm6hiYPl4lk6KNyU8upPM4=,iv:TZ9o5ioU/1kkcaZUbw+z6J0GD4DYQt48V5Bjp4rZmhQ=,tag:LmZGwSBXvTHQulyCAUHQyA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
