apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yUUbRjvzBCzNNoqdVkcR5pJhkZJx0uLHoTdgRaf70LBu2IsX6aqtbVZ5yt8+i9r5Mo1sftKTNy7nq8ScMcqDKzyUQh0LkuXtTXQq17KznIS59NNkCFBd7MFUoasR76q+zz3y14m0cYZE9+2FeXdv5oGFiAJs682MeSij19XciFyPLic7JaFkTpXE07JRoq+Dkhx0Zs4GCHzdXD486CDbuLeBz+zRNzyAs8e1EW99KpUzeehZXEKzRnUFseLMvvsAbhZHxbYVODMGnKCMvAkzE/1p/BTOCVdwGeWSS55YYx+yeLs6h2Xjk8IJGS8P51SM+SWBMebr6CH9YQh/JPgV8r8X9VZ+Rx/Wo5gwWS45FHhyKTrO0WAeJbQ9xTrbVzBj,iv:wcRNxFvS6t1HejOhU44aLmBez1FHKIFMUbCyyvcRxpg=,tag:IyAQj02/btvemWcb9WxROw==,type:str]
    identity.pub: ENC[AES256_GCM,data:HZ+FpnYwC68IswbuJAeDq0xanRq13EUYSZ7+ANOipt7KqovQzMxAFaJS+9B2BYasfM4X0R0FTaLlWTgZIkWajWf0AQGoDxtn95Nb/+TGv5EOWRWcbCy8XL6OjjGqt9N4Vl0ccWFN5Q1g4sm7BQatcavOFXvGLOJG7CnMTeY8LmLFYsnGUbkr86FQqw1JKMg1/JZISGRZCW5qxuLP4F4jquWbLpd++S+ivPINk9YHPrNcbjp89pXPs3luQYLlVFgZE+xTrXqpFFKttgcMgQ==,iv:UbB6CTMN4V8XnaSs4CMhoHLWegTmWRYCpowIV+JzAQE=,tag:mIElySf+/pLTe4fJsQG/gw==,type:str]
    known_hosts: ENC[AES256_GCM,data:z9PZ69WzoiBeLz1lCqkFcWaOnymTcT8s2veRZXasecCoAilQ2aK9M4U5E/6+PcshecYi8ltQVfr/g2mte/qWYV/xIFPB2DvZ1VWqZFSILzUM0GbuvyYyWwmwlKtMC6XHTmSG/rvHU9Zil6beO7t/nNPxEH2tO/IJ5PPdIFshQzb8Cw6nSmRWr+6Vv1cWSGeceQKYJXPP32KtESvzlVoB0X9TsB+cgYJ+pLLf,iv:AlrC7lqFkjn6zHu2ofdoqjtpql9LYWlzanAYAQwOHQk=,tag:2zwadayFBf+iZ0eVaXfWRg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeXp6S1gxTlpZQWNZdjFI
            VTAxZm9jTEZIRDM1djVGWWpvRzZWazgvSUcwCkFWUzJRdFplR1gvbGdSL01vcWpG
            QXAxNnE4QWpZbEdXWHlCTE1hMUxZYnMKLS0tIHJJVXp0ODR2VnR5aExmcTJZcXlz
            RlA1RTlyYVRnS29wdWUyVkRqZnAxeE0Kawo0N7ohmIaX0d4GvSNZ/lm65Sq7NwDi
            ZKNshnHzt3yE+qirMRZEugBb77XdZtQiSABtAnphr8QAzLEDiOeSjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T19:30:03Z"
    mac: ENC[AES256_GCM,data:q442KjXgLIu9CTqDhpF0wtDs/Oer6Q0zwGuEHO8wsmx4kMVFrKZumxSKnN98AymFXeg1irpEFBwi+6uj4xvhkGoRZMO80RrIt5T6hXAeWsAVHiHa3dPplaKb8aAUyvt70NlOiT0BmDUBTVDajnf6GMEGCGYg6ThF48xvelCxhGI=,iv:Dp4yFLAv9l+8sJeSk6YrIGEt5PNMm/zt+hWhbgFySQw=,tag:QRz6wKsb3mzPL5gIvX4Eiw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
