apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ilgOHEexOIx9/sySULuov6+PlZArnP5D+nuUmTbRrnB/UN/YlRlnyneXdDxypj6fUJc0Vyt3oergPtnGP9oPHSYHDvKtvWoA9xPn9yvNeZK6Us+AJ2vdxRZjve4DZhU9gDTM6MylHvcLn/D49lzJwEmcI3xOMLETqo90ibrPiNWE/xt4nLOuY4J8FPjuraLXuJe7/lAnpf45a8fBZZVAuQZFq+mBE54Hc7OQUXM3E4oXR+Z7quQuz4jt2D77KNXVTMA8tSZ404OfN1tdUFgW1VnL6PNZx6IwrKIa4AqEUeGYFKQiu+yf/+6nTFjdmGMDftBKaq7M6h5y4eGGvRuECoUZAZBXjrtj7W7T4Oz4LapR/D8P9gU1PWGdcdUJQP5L,iv:sEJ5xwSEiI5CW8utohPkbV6xN7av0J/ZogvR95uTIB0=,tag:HQqJQk+HEZJgwvfhP6kxFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:0Xq+irEEOWFxq7xduj5Iegb85Q1/GPSbM/T/i6s7imelEfqAr7Ijco3l8F7BIsNThuF5YsjSi9n0S3P3EE3isp/Sgk+CYskQxCkWaLoaKw/WPrvDGfO9wl9ohdy1KRKGyAp4+Fy29o8VVeYpsebpbe+0hBUlGtZwi+dNjlpfW6kuKQ/OJYBWNQH0SMwcVeRpD54/igAStI28vzEZrqNAnz3skldCJ9VYFvCPnKk2Whc4Xo/mHukLqh+umbqTjU9R+Wt2K1eshtk4E3awPQ==,iv:vMh7yFw5wmJbMxsTtjBGEEq8PyosO8HZE2nhFmQDhIM=,tag:+39gCltDsb9Edh/HeONL1w==,type:str]
    known_hosts: ENC[AES256_GCM,data:Xdm73IK5to4czLA32MaRQDa3edOrroh0xPeu3rsqsGGkkqp8kBlKu75BoASF8YF6IkSpX4Is0WcNKcPcwV0BNWLXoaj3ijSa8yJfHclMI1tOgYtGt4lnaHYWWq3G5XcTXz6mw9zcw3k4cOunKofRAWmEl0nQeGhn6EqhrF6j/lJCS9Yu9z5CQ0NVrCYomSy/qjaJ+o4JgxVh7LC4L8yJm5Egj9escjgTGiLE,iv:Dp8Nk7s3IclMDoQOSpTewBdXfPK/jWrM+0JloREZe+Q=,tag:83j7xMVEwHJjYVYKJ3pWRA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRzkvSnVXTjNFR2pZMGMr
            Z1g4QWo3VlpsUXEwVjdqZ2syODU5ZGRvcWlZCkE0VXBhNVNwVkNyRXhxcVhWalFB
            WWFnWFRwbVNBM0JxQzgxTnBxckVUOFEKLS0tIC9jUnB5VU9kQnYwbzBaSitvdDJK
            aWoyazNWVENOZjJXYy95cEx0MXJUTHMK6dC4D5n/IIHnN1wqbdmUg6JlyM6kIbLc
            v4HELMx/4tJjtyuf937qP+7HLqXompIKFzdlZmp9CLs/JIvXPLM+GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T11:59:27Z"
    mac: ENC[AES256_GCM,data:Bb9xCvV7i1RJLQTzEXpxN0cZ6zjVP5JSpZ+HGXGO105fpw6OFw2flbdDBicTwngNQvMR4TusdJkmkDvg68vCJ6t7r/BFXUAiUxC3rCaq3ENcrLo6BYEUGdU0CizRmfpFSkN7TDQBeg0kBI7ModxhR0Rjjkfj9/x5RNYHXl0+SzM=,iv:Fe8SP/KkQmQ5aIjuto46dQJlk5lV77hucWGXC7r0EbM=,tag:BV7UWqIGKFm8OwEvE/+s6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
