apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5PfThvqhjbBGjmcspxx9IJU+6z/tw1bMHbruDzaBMYmjfZopJawlY7O9M0OmROjXNGGvPB57lu2om6agDbdhBtUwjOGCcFvtS/PHAEsH/rHN3ogEeFh2jOPfD+S+gQoBuZUP9hOVpEvCVwG01iwsPJZG+D2AnN9D1dvWBojC2eq4db0abRUuZVTObxEROEacrLxm4jVYx3PKuIcVPS1Fxq/vijrJDKYk2Y0PqxwgrLt71CbZFP8pHv68xkmULA3G1gc7sYZ9Y/4daB2xUKEkmT0IIALnieM16TvcPqPaDmOrIV0LvchuUxoA5EF+BzmbJO0ojSUYkSQMbfnnxgnEQ1e07WhbuHwaR7XMmUTMRO8B3rR6HIXS+Q86vRdbaFO/,iv:xLEIjId3WW72G9oWNhoDJiWDI/o28+jyyPuBoXyhBNg=,tag:1BSeX5d1Ar9f4t5GExw2og==,type:str]
    identity.pub: ENC[AES256_GCM,data:qUqP8zFM7YtbF/EQ+0pls05EwJQnTRAhOkr+TjmdA9x5NsxiwkUCSzudMVXTjtI2T+uqeiBHP7aAKZTFzUtSELieoCobH1LvImtcGVOq4OqCoOAXyYrd05ZM1kZWXEPqp/Ljjh6Og9RGKARYiNW7+92MFoL+uxWxqCVwSGeJrTTIv3ywmQQ/8LcBAToJaLwCAf82HhWJ/iObZNBXyXVy0SXrnv9cSFkzEFsHQxHgJIsMOr+Dz6WJGx+7oUOl0hwG5lskvl9gos+uCYcY6w==,iv:/4OoUQnjFva0tCxDC7wob9pXrGijA7boum84atujr5E=,tag:ZJLp6yn6IlNVViU40ZvYyA==,type:str]
    known_hosts: ENC[AES256_GCM,data:HpX8rJdacP8G4IQn+uB4gYzbNUX2HUN57SObkyVAEVBQOaO4E/3dKrAA2BjBhhWZTVl+hyk76bvZZFaRQVpv2hkTI2aDuvbLzIui9wQAhzVoY/VPt+MzEYqvPDVnkcmVAupbfMG13LKsJuTvDbAok2uNILa0w8FPQdt6ceDiHFhNiFi9TTTnMCb7Ih/+1mlhKoAeMuRagcnwN4wuzYFYRGZ/EdV21RU2ofyB,iv:2/WcSGzLCDb2Qy21IkTD6OYKMuCGM4nGRbn8y6D4GBY=,tag:PlrCuIqYuCALPOdgxdLqPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDenNZZkRxeHpTanBNNStL
            d2dPWE4zVmh3ekRGVHBBOTlDSzF6Z3hpdUZZCm1PcS9HaDBEVnBxT2I5SUtVREhw
            azhyd3ExV096eEFSUTg5QTBoUkpYbE0KLS0tIGtmc2xPK3R1Y0xvTno1VjZZKzBv
            eDZzVEMxcy9qUjVXYW1VckcyQXBNZzgKbrSGrUBdlsl+wbcR95mtquI2ehLshNmO
            dueGa5h2kYLeMrcXfd4A2CD0oRLZZfQvjUeylWXNqfr5Iffy9P7tlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T06:51:46Z"
    mac: ENC[AES256_GCM,data:tHcmpFgHvy9OWHXvjApcNqHCK1E2XtbyAKTUPbLEaRNCNUM1JArR1k/fJ3n0hHZ/Ii5zM3DUP/JEn0jagQwKDTseZ0H175QQHS796D+5/CBDVbvSotTrX1Dz/5dMCBlQ+dY2YsizXNdbivMLmqEOXs/fTNKkODgF8sjiaKTRrCg=,iv:vaOGyWO/RLPaiXEXtkeahVZAsZjj3nqV1cp6RXAZvGc=,tag:YBuMbb6wXbFFd/8BYZcRMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
